[package]
name = "rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rust"
crate-type = ["cdylib","rlib"]

[dependencies]
pyo3 = "0.25.0"
pyo3-stub-gen = "0.10.0"
rand = "0.9.1"
