# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins

def add(a:builtins.int, b:builtins.int) -> builtins.int:
    r"""
    simply add to integers
    """

def guess_the_number() -> None: ...

